version: 2.1

jobs:
  build:
    docker:
      - image: centos:8
    steps:
      - run:
          command: |
            dnf update -y
            dnf install -y git
          name: Installing Git
      - checkout # Import the Git project into the container
      - run:
          command: |
            dnf groupinstall -y 'development tools'
            dnf install -y bzip2-devel expat-devel gdbm-devel ncurses-devel openssl-devel readline-devel wget sqlite-devel tk-devel xz-devel zlib-devel libffi-devel
            wget https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz
            tar -xf Python-3.7.9.tgz
            cd ./Python-3.7.9
            ./configure --enable-optimizations
            make -j 2
            make install
            python3 --version
          name: Compiling Python 3.7
      - run:
          command: |
            curl -LsS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash
            dnf install -y MariaDB-client MariaDB-common MariaDB-shared MariaDB-devel 
            mysql --version
          name: Installing MariaDB
      - run:
          command: |
            wget https://bootstrap.pypa.io/get-pip.py
            python3 ./get-pip.py
            python3 -m pip --version
          name: Installing pip
      - run:
          command: |
            python3 -m pip install -r requirements.txt
            python3 -m pip install -U codecov
            python3 -m pip install -U pytest-cov
          name: Downloading pip modules
      - run:
          command: |
            sed -i '/\[mysqld\]/ a event_scheduler=ON\nuserstat=1\nperformance_schema=ON' /etc/my.cnf.d/mariadb-server.cnf
            systemctl restart mariadb
          name: Configuring MariaDB
      - run:
          command: |
            mariadb < extra/myanimebot-init.sql
            mariadb -e "CREATE USER IF NOT EXISTS 'myanimebot'@'localhost' IDENTIFIED BY 'myPassword'; GRANT ALL PRIVILEGES ON myanimebot.* TO 'myanimebot'@'localhost'; FLUSH PRIVILEGES;"
          name: Importing the Database
      - run:
          command: |
            mkdir "logs"
            sed 's/token = 123456789ABCDEF987654321FEDCBA/token = '"$DISCORD_TOKEN"'/' myanimebot.example.conf > myanimebot.conf
          name: Configuring MyAnimeBot
      - run:
          command: |
            python3 -m pytest tests
          name: Testing the application

workflows:
  main:
    jobs:
      - build
