version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7
      - image: mariadb:10.5.8
    environment:
      PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: | # Install dependencies
          name: Install dependencies
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install -f requirements.txt
          name: Pipenv install dependencies
      - run:
          command: |
            python --version
            echo "Hello World"
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
