from myanimebot.commands.about import about_cmd
from myanimebot.commands.add_user import add_user_cmd
from myanimebot.commands.delete_user import delete_user_cmd
from myanimebot.commands.help import help_cmd
from myanimebot.commands.here import here_cmd
from myanimebot.commands.info import info_cmd
from myanimebot.commands.ping import ping_cmd
from myanimebot.commands.role import role_cmd
from myanimebot.commands.stop import stop_cmd
from myanimebot.commands.top import top_cmd